# Nixpacks configuration for Railway deployment
[variables]
NIXPACKS_BUILD_DIR = "frontend"

[phases.build]
dependsOn = ["install"]
cmds = ["echo 'Building frontend application...'"]

[phases.install]
dependsOn = ["setup"]
cmds = ["pip install -r requirements.txt"]

[phases.setup]
nixPkgs = ["python311", "pip"]
aptPkgs = []

[start]
cmd = "./start.sh"
