[build]
builder = "nixpacks"

[deploy]
startCommand = "cd frontend && streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true --server.enableCORS=false --server.enableXsrfProtection=false"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
# Frontend will be deployed on Railway
BACKEND_URL = "https://yt-bot-backend-8302f5ba3275.herokuapp.com"
NIXPACKS_PYTHON_VERSION = "3.11"
